### ISSUE TITLE
Got an unexpected keyword argument 'loop' starting Karapace

### ISSUE THREAD

**Issue by jahtux** [aiven/karapace#139]
Hello, 

I'm trying to test Karapace but I got the following error:

```python
karapace config_file
Karapace                MainThread      INFO            Karapace initialized
Exception ignored in: <function ClientSession.__del__ at 0x7fd02144b0e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py", line 269, in __del__
    if not self.closed:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py", line 894, in closed
    return self._connector is None or self._connector.closed
AttributeError: _connector
Traceback (most recent call last):
  File "/usr/local/bin/karapace", line 12, in <module>
    load_entry_point('karapace==2.0.1.dev97', 'console_scripts', 'karapace')()
  File "/usr/local/lib/python3.7/site-packages/karapace-2.0.1.dev97-py3.7.egg/karapace/karapace_all.py", line 56, in main
    kc = KarapaceAll(arg.config_file)
  File "/usr/local/lib/python3.7/site-packages/karapace-2.0.1.dev97-py3.7.egg/karapace/karapace_all.py", line 17, in __init__
    KafkaRest._init(self, config)
  File "/usr/local/lib/python3.7/site-packages/karapace-2.0.1.dev97-py3.7.egg/karapace/kafka_rest_apis/__init__.py", line 44, in _init
    self.serializer = SchemaRegistrySerializer(config_path=config_path)
  File "/usr/local/lib/python3.7/site-packages/karapace-2.0.1.dev97-py3.7.egg/karapace/serialization.py", line 122, in __init__
    registry_client = SchemaRegistryClient(registry_url)
  File "/usr/local/lib/python3.7/site-packages/karapace-2.0.1.dev97-py3.7.egg/karapace/serialization.py", line 71, in __init__
    self.client = Client(server_uri=schema_registry_url, client=aiohttp.ClientSession(loop=loop))
TypeError: __init__() got an unexpected keyword argument 'loop'
```

OS: CentOS Linux release 7.7.1908 (Core)
Python Version: Python 3.7.9 (default, Jan  4 2021, 17:06:19)

Config File options:

```json
{
    "advertised_hostname": "localhost",
    "bootstrap_uri": "ip-node-1:9092,ip-node-2:9092,ip-node-3:9092",
    "client_id": "kp-1",
    "compatibility": "FULL",
    "group_id": "schema-registry",
    "host": "",
    "log_level": "DEBUG",
    "port": 8081,
    "master_eligibility": true,
    "replication_factor": 1,
    "security_protocol": "PLAINTEXT",
    "ssl_cafile": null,
    "ssl_certfile": null,
    "ssl_keyfile": null,
    "karapace_rest": true,
    "karapace_registry": true,
    "topic_name": "_schemas",
    "session_timeout_ms": 10000
}
```

Can someone give me a tip on where I can investigate?

Thanks!

**Comment by hackaugusto** [comment]
It looks like the `loop` argument was removed https://github.com/aio-libs/aiohttp/pull/3580/ . Meanwhile this is not fixed you can use a pinned version as a quickfix `pip install aiohttp==3.5.4`.

**Comment by hackaugusto** [comment]
I double checked the problem. The argument was indeed removed a little while ago by #3580, however, this change is only commited to the alpha release. The fix is to install a stable release of `aiohttp`, which as `<4`

**Comment by jahtux** [comment]
@hackaugusto thank you!
