### ISSUE TITLE
Schema in API response contains unknown field "compatibility"

### ISSUE THREAD

**Issue by Oduig** [aiven/karapace#435]
# What happened?

Our Karapace Schema Registry, hosted with Aiven under the Kafka installation, is returning a field that should not be there according to the documentation, for a specific topic:

```curl -w '\n' -X GET https://avnadmin:redacted@redacted.aivencloud.com:10799/subjects/ourtopic-key/versions/latest
{"compatibility": "BACKWARD", "id": 44, "schema": "{\"fields\": [{\"name\": \"transactionid\", \"type\": \"string\"}], \"name\": \"OurTopicKey\", \"namespace\": \"com.example\", \"type\": \"record\"}", "subject": "ourtopic-key", "version": 1}
```

The field "compatibility" is not expected according to Schema Registry docs:
https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--subjects-(string-%20subject)-versions-(versionId-%20version)

This causes the Confluent library kafka-schema-registry-client to break.

# What did you expect to happen?

There should not be a field `compatibility` in the schema.

# What else do we need to know?

We use Kafka 3.2 (latest) from Aiven. Updating the client library does not help - there is no version in history that supports the field "compatibility" as part of a schema.

It appears that it has something to do with the compatibility setting of the schema itself. The problem only exists when the topic has an explicit compatibility (not the global one). Changing the compatibility level back to the default value, or to NONE, unfortunately does not un-set the compatibility setting. In theory, we could clear the schema-level compatibility setting for an immediate fix using DELETE. But it looks like this API endpoint is disabled by Aiven's Schema Registry: 405: Method Not Allowed.

Even if we delete the schema with ?permanent=true, the underlying compatibility setting persists, so we can never un-set it after setting it.

I will continue to work on a workaround on our end, and also reported the issue via Aiven support. Due to the nature of the bug, I expect this is a bug in Karapace and not just in Aiven's Schema Registry. Please advise us if there is any quick fix we can attempt.

**Comment by Oduig** [comment]
For completeness sake and Googlability, here is the stack trace from kafka-schema-registry-client.

```
22/08/01 14:33:29 ERROR ScalaDriverLocal: User Code Stack Trace: 
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "compatibility" (class io.confluent.kafka.schemaregistry.client.rest.entities.Schema), not marked as ignorable (4 known properties: "version", "schema", "id", "subject"])
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 466] (through reference chain: io.confluent.kafka.schemaregistry.client.rest.entities.Schema["compatibility"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3250)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:221)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:265)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:524)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:516)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getLatestSchemaMetadata(CachedSchemaRegistryClient.java:275)
        (...)
```

**Comment by Oduig** [comment]
FYI for anyone else arriving at the problem, here is a JAR file that can be used as a monkey patch. If you remove the .zip extension and include the jar in your classpath, it replaces a class in the `kafka-schema-registry-client`. The replacement class is configured to ignore the unknown property `compatibility`. Not a real fix - but a decent workaround.

[kafka-schema-registry-client-5.3.4-monkey-patch.jar.zip](https://github.com/aiven/karapace/files/9241728/kafka-schema-registry-client-5.3.4-monkey-patch.jar.zip)

**Comment by Oduig** [comment]
Hi, thanks for taking quick action on this. I wonder, when could we expect the Aiven hosted Karapace instance to have the update?
No rush, just looking for a timeframe so we can follow up and upgrade our cluster :)

**Comment by tvainika** [comment]
@Oduig Yesterday I created Karapace 3.3.1 release. Aiven hosted platform will receive this as optional maintenance update soon (a day or two to roll it out).
