### ISSUE TITLE
not able to install karapace manaully using pythin 3.8

### ISSUE THREAD

**Issue by rajsolanki73** [aiven/karapace#617]
Hi 

I am trying to install karapce manually using python 3.8

python3.8 setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    version_for_setup_py = version.get_project_version()
  File "/opt/karapace/karapace-3.5.0/version.py", line 56, in get_project_version
    raise RuntimeError(f"version not available from git or from file {str(version_file)!r}")
RuntimeError: version not available from git or from file '/opt/karapace/karapace-3.5.0/karapace/version.py'

**Comment by rajsolanki73** [comment]
I should have searched searched issues here . I used git clone and it works.

**Comment by aiven-anton** [comment]
@rajsolanki73 I'm glad you figured it out, setup requires to be able to determine a version and as you figured out, when using git Karapace will use the git history to determine a version. You could also manually set a version with the `KARAPACE_VERSION` environment variable. I'll leave this issue open, as I suspect we should update installation instructions in documentation.
