### ISSUE TITLE
having issues with connecting karapace (no docker ) to kafla with SSL 

### ISSUE THREAD

**Issue by rajsolanki73** [aiven/karapace#618]
I installed karapace without docker using instructions from [here.](https://github.com/aiven/karapace/issues/408) 

Here is my config.

```
{
    "access_logs_debug": false,

    "advertised_hostname": "redacted.server.com",

    "bootstrap_uri": "redacted.server.com:#####",

    "rest_authorization": false,

    "client_id": "sr-1",

    "compatibility": "FULL",

    "group_id": "CN=redacted,OU=IT,O=myorg.,L=myCity,ST=mystate,C=US",

    "host": "redacted.server.com",

    "log_level": "DEBUG",

    "port": 8081,

    "registry_ca": null,

    "replication_factor": 1,

    "security_protocol": "SSL",

    "ssl_cafile": "/opt/kafka/config/ssl/redacted.server.com.pem",

    "ssl_certfile": "/opt/kafka/config/ssl/redacted.server.com.jks",

    "ssl_keyfile": "/opt/kafka/config/ssl/redacted.server.com.jks",

    "ssl_password" : "^%$#@!^&",

    "sasl_mechanism": null,

    "sasl_plain_username": null,

    "sasl_plain_password": null,

    "karapace_rest": true,

    "karapace_registry": true,

    "registry_authfile": null,

    "topic_name": "_schemas",

    "protobuf_runtime_directory": "runtime",

    "session_timeout_ms": 10000
}
```

when i start my karapace giving above config file i get following error.

```
AttributeError: 'socket' object has no attribute 'do_handshake'
kafka.producer.kafka MainThread INFO            Closing the Kafka producer with 0 secs timeout.
kafka.producer.kafka MainThread INFO            Proceeding to force close the producer since pending requests could not be completed within timeout 0.
kafka.producer.sender kafka-python-producer-1-network-thread    ERROR           Uncaught error in kafka producer I/O thread
Traceback (most recent call last):
  File "/opt/karapace/raj/karapace/requirements/venv/lib/python3.8/site-packages/kafka/producer/sender.py", line 60, in run
    self.run_once()
  File "/opt/karapace/raj/karapace/requirements/venv/lib/python3.8/site-packages/kafka/producer/sender.py", line 160, in run_once
    self._client.poll(timeout_ms=poll_timeout_ms)
  File "/opt/karapace/raj/karapace/requirements/venv/lib/python3.8/site-packages/kafka/client_async.py", line 592, in poll
    self._maybe_connect(node_id)
  File "/opt/karapace/raj/karapace/requirements/venv/lib/python3.8/site-packages/kafka/client_async.py", line 402, in _maybe_connect
    conn.connect()
  File "/opt/karapace/raj/karapace/requirements/venv/lib/python3.8/site-packages/kafka/conn.py", line 440, in connect
    if self._try_handshake():
  File "/opt/karapace/raj/karapace/requirements/venv/lib/python3.8/site-packages/kafka/conn.py", line 519, in _try_handshake
    self._sock.do_handshake()
AttributeError: 'socket' object has no attribute 'do_handshake'
kafka.conn           Thread-1 DEBUG     <BrokerConnection node_id=bootstrap-0 host=redacted.server.com:####### <disconnected> [unspecified None]>: creating new socket
kafka.producer.sender kafka-python-producer-1-network-thread    DEBUG           Beginning shutdown of Kafka producer I/O thread, sending remaining records.
kafka.producer.kafka MainThread DEBUG           The Kafka producer has closed.
```

Any suggestions on what am i missing  ?

**Comment by rajsolanki73** [comment]
i resolved the issue.  I needed ,pem and .key file instead of jks
